### ISSUE TITLE
publishing over existing Lambda function

### ISSUE THREAD

**Issue by tbertenshaw** [joaoasrosa/AWSLambdaDemo#1]
Hi @joaoasrosa , 
  I looked to see if i could raise an issue (query) in your lambda step repo but couldn't see the option.

I've successfully used your step template to publish to lambda, the only problem is it seems to only work for initial publishing, you cannot update/publish over an existing function. This it only works the first time. I'm not sure if there is a missing cmdline parameter which will resolve this? 

Since my particular lambda function has triggering configuration which is done in the portal (i.e. triggered from a s3 object creation) i cannot destroy and republish. So the ability to update is needed if possible. Do you know if there is a way to achieve this?

Thanks
Tim

**Comment by joaoasrosa** [comment]
Hi @tbertenshaw,

Thanks for the feedback. That use case wasn't covered.
However, it is possible to update the lambda function code with another command.

AWS API was a cmd to update the lambda code. The update lambda function cmd only updates the code itself, not the configuration.
It is acceptable if the lambda function exists to update the code?

Cheers, João Rosa

**Comment by tbertenshaw** [comment]
Hi @joaoasrosa ,
  If i understand what you are saying/asking. then i think in the case of lambda functions which are published from octopus as part of a CI from teamcity. you would want to create or update from the same publish.  I don't know how the the octopus templates/functionlaity works but assume it calls AWS powershell commands in the background passing in the arguments specified in the template? if so could it be changed to update if exists? or another steptemplate for existing functions?

That would be amazing if so.

Cheers
Tim

**Comment by joaoasrosa** [comment]
Hi @tbertenshaw ,
The Octopus template can be enhanced to work in that way since the AWS API was methods to check if the lambda function exists.
This will cover the requirements?

Cheers, João Rosa

**Comment by tbertenshaw** [comment]
yes that would be great.!

Tim Bertenshaw

**Comment by joaoasrosa** [comment]
@tbertenshaw the PM (https://github.com/OctopusDeploy/Library/pull/499) was created. Waiting for the merge.

**Comment by tbertenshaw** [comment]
Thats great @joaoasrosa !

**Comment by joaoasrosa** [comment]
@tbertenshaw closing the issue since the PR was merged.

**Comment by tbertenshaw** [comment]
Hi @joaoasrosa  thats amazing !

Incidentally (quick question) if you already have an octopus deployment created using this step template. how do you get the new version? do you delete and readd? and do you need to reimport the step template library on your octopus server?

Cheers
Tim

**Comment by joaoasrosa** [comment]
I'm using Octopus version 3.7.12, and I had imported the step from the library.
If you go to the step, and click settings, you can update from there.
